spring:

#    datasource:
#        url: jdbc:h2:tcp://localhost:9092/test
#        url: jdbc:h2:mem:test;MV_STORE=FALSE

#    jpa:
#        hibernate:
#            ddl-auto: update

    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
            indent_output: true

        mapper:
            AUTO_DETECT_FIELDS: false
            REQUIRE_SETTERS_FOR_GETTERS: true