INSERT INTO CAR_MAKE (NAME) VALUES ('Ford'); -- 1
INSERT INTO CAR_MAKE (NAME) VALUES ('Toyota'); -- 2
INSERT INTO CAR_MAKE (NAME) VALUES ('Audi'); -- 3
INSERT INTO CAR_MAKE (NAME) VALUES ('Tesla'); -- 4

INSERT INTO CAR_TYPE (NAME, HAS_OIL, HAS_SPARKPLUGS) VALUES ('Gas', TRUE, TRUE); -- 1
INSERT INTO CAR_TYPE (NAME, HAS_OIL, HAS_SPARKPLUGS) VALUES ('Diesel', TRUE, FALSE); -- 2
INSERT INTO CAR_TYPE (NAME, HAS_OIL, HAS_SPARKPLUGS) VALUES ('Hybrid', TRUE, TRUE); -- 3
INSERT INTO CAR_TYPE (NAME, HAS_OIL, HAS_SPARKPLUGS) VALUES ('Electric', FALSE, FALSE); -- 4

INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('F-150', 1, 1);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Super Duty', 1, 2);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Fusion', 1, 3);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Focus', 1, 4);

INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Rav4', 2, 1);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Prius', 2, 3);

INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('A8 L', 3, 1);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('A3 e-tron', 3, 3);

INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Roadster', 4, 4);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Model S', 4, 4);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Model X', 4, 4);
INSERT INTO CAR_MODEL (NAME, CAR_MAKE_ID, CAR_TYPE_ID) VALUES ('Model 3', 4, 4);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Joshua', 'Bellamy-Henn');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('James', 'Smith');

INSERT INTO CAR (YEAR, CAR_MODEL_ID, CUSTOMER_ID) VALUES (2012, 5, 1);
INSERT INTO CAR (YEAR, CAR_MODEL_ID, CUSTOMER_ID) VALUES (2014, 1, 2);

INSERT INTO SERVICE_RECORD (DATE_SERVICED, ODOMETER_READING, SERVICE_SPARK_PLUGS_CHANGED, SERVICE_OIL_CHANGED, SERVICE_TIRE_ROTATED, CAR_ID, CUSTOMER_ID) VALUES (NOW(), 1000, TRUE, TRUE, TRUE, 1, 1);
INSERT INTO SERVICE_RECORD (DATE_SERVICED, ODOMETER_READING, SERVICE_SPARK_PLUGS_CHANGED, SERVICE_OIL_CHANGED, SERVICE_TIRE_ROTATED, CAR_ID, CUSTOMER_ID) VALUES (NOW(), 1000, TRUE, TRUE, TRUE, 2, 2);
